---
- name: Update apt
  hosts: all
  become: yes

  tasks:
    - name: Update repositories
      ansible.builtin.apt:
          cache_valid_time: 86400
          update_cache: yes

    - name: Install jq
      ansible.builtin.apt:
        name: jq
        state: present

- name: Install ipfs
  hosts: all
  become: yes
  roles:
    - ipfs

- name: Configure ipfs
  hosts: all
  tasks:
    - name: Run ipfs init
      ansible.builtin.command:
        cmd: ipfs init --profile=lowpower
        creates: ~/.ipfs/config

- name: Start ipfs
  hosts: all
  roles:
    - config
