---
- name: Download kubo
  ansible.builtin.get_url:
    url: "https://github.com/ipfs/kubo/releases/download/{{ipfs_version}}/kubo_{{ipfs_version}}_linux-amd64.tar.gz"
    dest: "/tmp/kubo.tar.gz"
    mode: 0644

- name: Extract kubo
  ansible.builtin.unarchive:
    src: "/tmp/kubo.tar.gz"
    dest: "/tmp/"
    remote_src: true
    creates: "/tmp/kubo/"

- name: Move ipfs
  ansible.builtin.copy:
    src: /tmp/kubo/ipfs
    dest: /usr/local/bin/ipfs
    remote_src: true
    owner: root
    group: root
    mode: '0755'

- name: Cleanup archive
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/kubo"
    - "/tmp/kubo.tar.gz"

- name: Open tcp 4001
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    destination_port: 4001
    ctstate: NEW
    jump: ACCEPT
    comment: Allow IPFS communication

- name: Open udp 4001
  ansible.builtin.iptables:
    action: insert
    chain: INPUT
    protocol: udp
    destination_port: 4001
    ctstate: NEW
    jump: ACCEPT
    comment: Allow IPFS UDP communication

- name: Save iptables
  ansible.builtin.shell:
    cmd: iptables-save | grep -v f2b- > /etc/iptables/rules.v4
