---
- name: Set LowWater
  ansible.builtin.shell:
    cmd: jq ".Swarm.ConnMgr.LowWater = 600" ~/.ipfs/config > tmp; mv tmp ~/.ipfs/config

- name: Set HighWater
  ansible.builtin.shell:
    cmd: jq ".Swarm.ConnMgr.HighWater = 900" ~/.ipfs/config > tmp; mv tmp ~/.ipfs/config

- name: Create systemd script
  become: yes
  ansible.builtin.template:
    src: ipfs.service
    dest: /etc/systemd/system/ipfs.service
    owner: root
    group: root
    mode: '0644'
  notify: restart systemctl

- name: Enable ipfs service
  become: yes
  ansible.builtin.systemd:
    name: ipfs
    state: stopped
    enabled: yes

# Bootstrap from https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list
- name: Copy ipfs bootstrap list
  ansible.builtin.copy:
    src: ipfs_bootstrap
    dest: ~/ipfs_bootstrap
    mode: '0400'

- name: Reset ipfs bootstrap list
  ansible.builtin.shell:
    cmd: ipfs bootstrap rm --all

- name: Set ipfs bootstrap list
  ansible.builtin.shell:
    cmd: cat ~/ipfs_bootstrap | ipfs bootstrap add

- name: Cleanup bootstrap
  ansible.builtin.file:
    path: ~/ipfs_bootstrap
    state: absent

- name: Start ipfs service
  become: yes
  ansible.builtin.systemd:
    name: ipfs
    state: started
